### ISSUE TITLE
Rank editor

### ISSUE THREAD

**Issue by Pinklord344** [PetrTech/ULTRAKILL-Save-Editor#1]
How do I access this page? I want to be able to edit my ranks.
![image](https://github.com/user-attachments/assets/ee1b801e-b9a1-4230-8533-6ede3f4672e2)

**Comment by PetrTech** [comment]
Hi, I haven't updated the save editor in quite some time now! It's made for older versions of the game (specifically pre-act3), thus it doesn't work with the latest version (tested). I'll let you know in the future if I decide to continue with this project.
PRs are still welcome of course (the code is a mess though 😅)
